### ISSUE TITLE
Question: Stream Network Missing Main Stem

### ISSUE THREAD

**Issue by reidi** [dtarb/TauDEM#34] opened 2016-01-08 21:31 UTC
I'm delineating watersheds and stream network and having an odd problem.  Although the wshed layer and stream network are being created, the main stem is missing.  All the tributaries are there, but the main stem is not.  Also, continuously along that missing channel the wsheds are missing - the grid has no data cells in those areas.  Script runs to completion, no errors or warnings.

Thanks for any help you can provide.

Ian
.
TauDEM 5.1.2 command line, mpiexec (Microsoft HPC Pack 2012 MS-MPI Redistributable Pack)
Windows 7, Intel i7, 16GB
Data source: USGS 1/3 arcsec DEM downloaded from TheNationalMap, projected to an Oregon LCC projection.
Area: ~1600 km2

Here is a small area that shows the problem:
![image](https://cloud.githubusercontent.com/assets/16615792/12209771/257f2cdc-b60a-11e5-9ea5-398148fcbd98.png)

Here is the script I am using:
************************************
REM @echo off
REM Get output directory
echo PWD is %cd%
set /p UserInputPath= "Enter output directory: "
set op=%cd%\%UserInputPath%
md %op%
if ERRORLEVEL 1 EXIT /B
echo Output path is %op%

REM FILL
mpiexec -n 8 PitRemove mud.tif

REM FLOWDIR
mpiexec -n 8 D8Flowdir -p mudp.tif -sd8 %op%\mudsd8.tif -fel mudfel.tif
mpiexec -n 8 DinfFlowdir -ang %op%\mudang.tif -slp %op%\mudslp.tif -fel mudfel.tif

REM CONTRIB AREA
mpiexec -n 8 AreaD8 -p mudp.tif -ad8 %op%\mudad8.tif
mpiexec -n 8 AreaDinf -ang %op%\mudang.tif -sca %op%\mudsca.tif
REM mpiexec -n 8 Aread8 -p mudp.tif -o outlet.shp -ad8 %op%\mudad8o.tif
mpiexec -n 8 Aread8 -p mudp.tif -ad8 %op%\mudad8o.tif

REM GRIDNET
mpiexec -n 8 Gridnet -p mudp.tif -plen %op%\mudplen.tif -tlen %op%\mudtlen.tif -gord %op%\mudgord.tif

REM PEUKERDOUGLAS
mpiexec -n 8 PeukerDouglas -fel mudfel.tif -ss %op%\mudss.tif

REM PEUKERDOUGLAS STREAM DELINEATION
REM mpiexec -n 8 Aread8 -p mudp.tif -o mudoutlet2.shp -ad8 %op%\mudssa.tif -wg %op%\mudss.tif
mpiexec -n 8 Aread8 -p mudp.tif -ad8 %op%\mudssa.tif -wg %op%\mudss.tif
mpiexec -n 8 Dropanalysis -p mudp.tif -fel mudfel.tif -ad8 %op%\mudad8.tif -ssa %op%\mudssa.tif -drp %op%\muddrp.txt -o 

mudoutlet.shp -par 5 1500 16 0
mpiexec -n 8 Threshold -ssa %op%\mudssa.tif -src %op%\mudsrc.tif -thresh 300

REM STREAM NETWORK
mpiexec -n 8 Streamnet -fel mudfel.tif -p mudp.tif -ad8 %op%\mudad8.tif -src %op%\mudsrc.tif -ord %op%\mudord3.tif -tree 

%op%\mudtree.dat -coord %op%\mudcoord.dat -net %op%\mudnet.shp -w %op%\mudw.tif -o sws_outlets.shp
**************************************

**Comment by dtarb** [comment] 2016-01-09 00:29
It is likely that the problem is edge contamination.  See http://hydrology.usu.edu/taudem/taudem5/help53/D8ContributingArea.html for an explanation.  This is defined as the possibility that a contributing area value may be underestimated due to grid cells outside of the domain not being counted. This occurs when drainage is inwards from the boundaries or areas with no data values for elevation. The algorithm recognizes this and reports "no data" for the contributing area. It is common to see streaks of "no data" values extending inwards from boundaries along flow paths that enter the domain at a boundary. This is the desired effect and indicates that contributing area for these grid cells is unknown due to it being dependent on terrain outside of the domain of data available. Edge contamination checking may be turned off in cases where you know this is not an issue or want to ignore these problems, if for example, the DEM has been clipped along a watershed outline.  

You can turn off edge contamination checking by putting "-nc" on command lines of the affected functions (AreaD8, AreaDinf, ...), but it is best resolved by extending the DEM to include the missing terrain.

**Comment by reidi** [comment] 2016-01-09 19:51
The -nc solution worked well for allowing the stream network to be built.
However, I still have the chain of NULL catchments along the channel.  Any
way to deal with that?  Ideally those catchments would be created using the
TauDEM tool.  I'm using QGIS and the topology functions are limited so it
would be difficult to "patch" those missing wsheds in.  I'm resisting
processing the entire watershed because it is quite large - the John Day
River in central Oregon.

Many thanks for your assistance.

**Comment by dtarb** [comment] 2016-01-09 20:59
I do not think you should get null catchments along the channel.  I just tried to replicate your procedure as closely as I could with some of my data and did not get null catchments along the channel.  Check that you used the -nc option for all the times you evaluated AreaD8.  There should be a 1:1 relation between links (segments) in the stream network and catchments so I do not know how you are ending up with null catchments but a filled in stream network.

**Comment by reidi** [comment] 2016-01-10 06:21
Operator error on my part apparently.  I've carefully rechecked the
script/parameters and think I missed adding the "-nc" flag in the
 PeukerDouglas Stream Delineation AreaD8 section.  I'm now getting good
results.  95% of the area of interest is not impacted by edge
contamination, but the area contains frontals to a major river system in
Oregon - the John Day River.

A possible point of interest, the results will inform range management on
the 64,000 acre Washington Family Ranch, formerly the Big Muddy Ranch owned
by the organization led by Bhagwan Shree Rajneesh in the 1980's.

Thanks again for your patient assistance.

**Closed** 2016-01-10 14:54 UTC
Labels: Answer

**Comment by rmuellerjr** [comment] 2018-03-16 13:32
This is an old post, but I will add my 2 cents as I ran across the same problem. 
Navigating through the ArcGIS Start guide, this appears to occur when I was trying to use the d-infinity contributing area into stream definition by threshold.

I.E.
 "D-Infinity Contributing Area" output (i.e. _sca.tif) as the input to the next step; "Stream Definition by Threshold" tool rather than the "D8 Contributing area grid" (or "_ad8.tif" input).
